name: CI
on:
  push:
    branches:
      - master

jobs:
  ci:
    name: RELEASE
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ci
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run start
